/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Difficulty = IDL.Variant({
  'intermediate' : IDL.Null,
  'beginner' : IDL.Null,
  'advanced' : IDL.Null,
  'exam' : IDL.Null,
});
export const Time = IDL.Int;
export const PracticeSession = IDL.Record({
  'wpm' : IDL.Nat,
  'difficulty' : Difficulty,
  'timestamp' : Time,
  'accuracy' : IDL.Float64,
});

export const idlService = IDL.Service({
  'getSessionHistory' : IDL.Func([], [IDL.Vec(PracticeSession)], ['query']),
  'recordSession' : IDL.Func([IDL.Nat, IDL.Float64, Difficulty], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Difficulty = IDL.Variant({
    'intermediate' : IDL.Null,
    'beginner' : IDL.Null,
    'advanced' : IDL.Null,
    'exam' : IDL.Null,
  });
  const Time = IDL.Int;
  const PracticeSession = IDL.Record({
    'wpm' : IDL.Nat,
    'difficulty' : Difficulty,
    'timestamp' : Time,
    'accuracy' : IDL.Float64,
  });
  
  return IDL.Service({
    'getSessionHistory' : IDL.Func([], [IDL.Vec(PracticeSession)], ['query']),
    'recordSession' : IDL.Func([IDL.Nat, IDL.Float64, Difficulty], [], []),
  });
};

export const init = ({ IDL }) => { return []; };